[package]
name = "pinto"
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
version = "0.10.6"

[[bin]]
name = "pinto"
path = "src/main.rs"

[features]
default = []
cuda = [
    "legume-numeric/cuda",
    "data-beans/cuda",
    "graph-embedding-util/cuda",
]
metal = [
    "legume-numeric/metal",
    "data-beans/metal",
    "graph-embedding-util/metal",
]
hdf5 = ["data-beans/hdf5"]

[dependencies]
cnv = { workspace = true }
data-beans = { workspace = true, features = ["aux", "alg"] }
legume-numeric = { workspace = true, features = ["matrix", "param", "candle", "mcmc"] }
graph-embedding-util = { workspace = true }
parquet = { workspace = true }
plot-utils = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

dashmap = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
rayon = { workspace = true }
tempfile = { workspace = true }
rand = { workspace = true }
ndarray = { workspace = true }
rand_distr = { workspace = true }
nalgebra = { workspace = true }
nalgebra-sparse = { workspace = true }
wide = { workspace = true }

special = { workspace = true }
indicatif = { workspace = true }
log = { workspace = true }
colored = { workspace = true }
rustc-hash = { workspace = true }
