

```{sh compile_or_install_if_needed}
cargo install --path .
cargo install --path ../data-beans
```

```{sh download_10x_data}
[ -f Xenium_V1_human_Pancreas_FFPE_outs.zip ] || \
	curl -O https://cf.10xgenomics.com/samples/xenium/2.0.0/Xenium_V1_human_Pancreas_FFPE/Xenium_V1_human_Pancreas_FFPE_outs.zip
if ! [ -d temp ] ; then
	mkdir -p temp
	unzip Xenium_V1_human_Pancreas_FFPE_outs.zip -d ./temp
fi

## create temporary files
[ -f temp7.h5 ] || data-beans from-zarr temp/cell_feature_matrix.zarr.zip -o temp7 --backend hdf5	
```

```{sh run_pinto_svd}
cargo install --path .

RUST_LOG=info pinto svd temp7.h5 -c temp/cells.parquet --coord-column-names x_centroid,y_centroid -o temp7 --preload-data -t 10

RUST_LOG=info pinto propensity -z temp7.latent.parquet -e temp7.coord_pairs.parquet -d temp7.h5 -k 6 -o temp7
```

```{r}
.dt <-
    arrow::read_parquet("temp7.collapsed_pairs.parquet") %>%
    as.data.table

quartz()
ggplot(.dt, aes(left_x_centroid, left_y_centroid, xend=right_x_centroid, yend=right_y_centroid)) +
    scale_y_reverse() +
    theme_void() +
    geom_point(stroke=0) +
    geom_segment()
```

```{sh}
cargo install --path ../senna
senna topic temp7.h5 -o temp_senna -t 10

```


```{r}
library(dplyr)
library(data.table)
library(ggplot2)

.genes <- arrow::read_parquet("temp7.genes.parquet")

as.data.table(.genes)[order(`log_mean`, decreasing=T), head(.SD, 5), by = .(column)]

.pairs <- arrow::read_parquet("temp7.coord_pairs.parquet")

.dt <- arrow::read_parquet("temp/cells.parquet") %>% as.data.table

.prop <- arrow::read_parquet("temp7.propensity.parquet") %>%
    as.data.table %>%
    melt(id.vars = "row") %>%
    na.omit() %>% 
    rename(cell_id = row)

.latent <- arrow::read_parquet("temp7.latent.parquet")

## .prop <- arrow::read_parquet("temp_senna.latent.parquet") %>%
##     as.data.table %>%
##     melt(id.vars = "row") %>%
##     dplyr::mutate(value = exp(value)) %>% 
##     dplyr::rename(cell_id = row)

.dt.show <- .prop %>%
    left_join(.dt[, .(cell_id, x_centroid, y_centroid, total_counts)]) %>%
    na.omit()

quartz()
ggplot(.dt.show[sample(.N)][value > .5],
       aes(x_centroid, y_centroid, colour=variable, size=value)) +
    facet_wrap(~variable, nrow=2) +
    scale_y_reverse() +
    theme_void() +
    geom_point(stroke=0) +
    scale_colour_brewer(palette="Paired", guide="none") +
    scale_size_continuous(range=c(0,2), guide="none")

```


```{r}


```


