mod handlers;
mod hdf5_io;
mod interactive;
mod qc;
mod simulations;
mod sparse_data_visitors;
mod sparse_io;
mod sparse_io_vector;
mod sparse_matrix_hdf5;
mod sparse_matrix_zarr;
mod sparse_util;
mod utilities;

use crate::handlers::analysis::{
    run_simulate, run_simulate_multimodal, run_stat, RunSimulateArgs, RunSimulateMultimodalArgs,
    RunStatArgs,
};
use crate::handlers::builders::{
    run_build_from_10x_matrix, run_build_from_10x_molecule, run_build_from_h5ad,
    run_build_from_mtx, run_build_from_zarr_triplets, From10xMatrixArgs, From10xMoleculeArgs,
    FromH5adArgs, FromMtxArgs, FromZarrArgs,
};
use crate::handlers::inspection::{
    show_info, take_column_names, take_columns, take_row_names, take_rows, InfoArgs,
    TakeColumnNamesArgs, TakeColumnsArgs, TakeRowNamesArgs, TakeRowsArgs,
};
use crate::handlers::listing::{list_h5, list_zarr, ListH5Args, ListZarrArgs};
use crate::handlers::merging::{
    align_backends, run_merge_backend, run_merge_mtx, AlignDataArgs, MergeBackendArgs, MergeMtxArgs,
};
use crate::handlers::transformation::{
    reorder_rows, run_squeeze, subset_columns, subset_rows, ReorderRowsArgs, RunSqueezeArgs,
    SubsetColumnsArgs, SubsetRowsArgs,
};
use crate::simulations::deconv::{generate_convoluted_data, SimConvArgs};

use clap::{Parser, Subcommand};

fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();

    if cli.verbose {
        std::env::set_var("RUST_LOG", "info");
    }
    env_logger::init();

    match &cli.commands {
        Commands::FromMtx(args) => {
            run_build_from_mtx(args)?;
        }
        Commands::ListH5(args) => {
            list_h5(args)?;
        }
        Commands::ListZarr(args) => {
            list_zarr(args)?;
        }
        Commands::FromZarr(args) => {
            run_build_from_zarr_triplets(args)?;
        }
        Commands::From10xMatrix(args) => {
            run_build_from_10x_matrix(args)?;
        }
        Commands::FromH5ad(args) => {
            run_build_from_h5ad(args)?;
        }
        Commands::From10xMolecule(args) => {
            run_build_from_10x_molecule(args)?;
        }
        Commands::Simulate(args) => {
            run_simulate(args)?;
        }
        Commands::SimulateConv(args) => {
            generate_convoluted_data(args)?;
        }
        Commands::SimulateMultimodal(args) => {
            run_simulate_multimodal(args)?;
        }
        Commands::Info(args) => {
            show_info(args)?;
        }
        Commands::Statistics(args) => {
            run_stat(args)?;
        }
        Commands::Squeeze(args) => {
            run_squeeze(args)?;
        }
        Commands::Columns(args) => {
            take_columns(args)?;
        }
        Commands::Rows(args) => {
            take_rows(args)?;
        }
        Commands::ColumnNames(args) => {
            take_column_names(args)?;
        }
        Commands::RowNames(args) => {
            take_row_names(args)?;
        }
        Commands::SubsetColumns(args) => {
            subset_columns(args)?;
        }
        Commands::SubsetRows(args) => {
            subset_rows(args)?;
        }
        Commands::AlignData(args) => {
            align_backends(args)?;
        }
        Commands::ReorderRows(args) => {
            reorder_rows(args)?;
        }
        Commands::MergeMtx(args) => {
            run_merge_mtx(args)?;
        }
        Commands::MergeBackend(args) => {
            run_merge_backend(args)?;
        }
    }

    Ok(())
}

#[derive(Parser, Debug)]
#[command(
    version,
    about = "Data Backend for Expedited Acquisition and Neighbourhood Search.",
    long_about = "Data Backend for Expedited Acquisition and Neighbourhood Search (data-beans).

We assume non-negative sparse matrices were generated by single-cell omics (feature x cell).
This tool creates a data structure for faster access, organized as follows:

    (root)
        ├── nrow
        ├── ncell
        ├── by_column
        │   ├── data
        │   ├── indices (row indices)
        │   └── indptr (column pointers)
        └── by_row
            ├── data
            ├── indices (column indices)
            └── indptr (row pointers)

For more details on each command, use '--help' after the command name."
)]
struct Cli {
    #[arg(short = 'v', long, global = true)]
    verbose: bool,

    #[command(subcommand)]
    commands: Commands,
}

#[derive(Subcommand, Debug)]
enum Commands {
    #[command(about = "Build backend from `mtx` file and associated `tsv` files")]
    FromMtx(FromMtxArgs),

    #[command(
        name = "from-10x-matrix",
        about = "Build backend from 10X Genomics feature-barcode matrix `h5`",
        long_about = "Build a backend from a 10X Genomics Cell Ranger feature-barcode matrix HDF5 file.\n\
		      Expected layout: matrix/{data,indices,indptr,barcodes,features/...}\n\
		      \n\
		      This is the `filtered_feature_bc_matrix.h5` or `raw_feature_bc_matrix.h5`\n\
		      output from Cell Ranger count/multi.\n\
		      \n\
		      Use --root-group-name, --data-field, etc. to customize field paths.\n\
		      Use --select-row-type to filter features (default: 'gene').",
        visible_alias = "from-h5"
    )]
    From10xMatrix(From10xMatrixArgs),

    #[command(
        about = "Build backend from AnnData `h5ad` file (CELLxGENE schema)",
        long_about = "Build a backend from an AnnData h5ad file (CELLxGENE schema v7, AnnData spec v0.1.0).\n\
		      \n\
		      Auto-detects sparse format (CSR/CSC) and transposes to (features x cells).\n\
		      Prefers raw/X (raw counts) over X (processed) when available.\n\
		      \n\
		      Additionally outputs:\n\
		      - {output}.cell_metadata.tsv.gz    (all obs columns per cell)\n\
		      - {output}.barcode_to_donor.tsv.gz (barcode-to-donor mapping, if donor_id exists)\n\
		      - {output}.sample_metadata.tsv.gz  (one row per donor, if donor_id exists)\n\
		      \n\
		      Column names become barcode@donor_id for multi-donor data.\n\
		      Use --select-row-type to filter by biotype (e.g., 'protein_coding')."
    )]
    FromH5ad(FromH5adArgs),

    #[command(
        name = "from-10x-molecule",
        about = "Build backend from 10X molecule_info.h5",
        long_about = "Build a backend by aggregating per-molecule counts from a 10X Genomics\n\
		      molecule_info.h5 file into a feature x cell sparse matrix.\n\
		      \n\
		      Each molecule has (barcode_idx, feature_idx, count, gem_group, library_idx).\n\
		      Molecules are filtered by --library-type and optionally by Cell Ranger's\n\
		      pass_filter (valid cell calls), then aggregated into count triplets.\n\
		      \n\
		      Barcode names are formatted as SEQUENCE-GEMGROUP (e.g., AAACCTGA-1).\n\
		      Handles multi-sample (cellranger aggr) and multi-library (CITE-seq) data."
    )]
    From10xMolecule(From10xMoleculeArgs),

    #[command(
        about = "Build backend from triplets in 10X Xenium `zarr`",
        long_about = "Build a backend from triplets in `zarr` format.\n\
		      Supports conversion and indexing for fast access."
    )]
    FromZarr(FromZarrArgs),

    #[command(
        about = "List contents of `h5` file",
        long_about = "List what are included in the `h5` file.\n\
		      Shows datasets, groups, and metadata."
    )]
    ListH5(ListH5Args),

    #[command(
        about = "List contents of `zarr` file",
        long_about = "List what are included in the `zarr` file.\n\
		      Displays structure and available arrays."
    )]
    ListZarr(ListZarrArgs),

    #[command(
        about = "Sort rows by name order",
        long_about = "Sort rows according to the order of row names specified in a row name file.\n\
		      Useful for aligning datasets and ensuring consistent row order."
    )]
    ReorderRows(ReorderRowsArgs),

    #[command(
        about = "Take columns and output dense matrix",
        long_about = "Take columns from the sparse matrix and save them to an `output` file as a dense matrix for quick examination.\n\
		      Useful for extracting subsets for visualization or analysis."
    )]
    Columns(TakeColumnsArgs),

    #[command(
        about = "Take rows and output dense matrix (transposed)",
        long_about = "Take rows from the sparse matrix and save them to an `output` file as a dense matrix for quick examination.\n\
		      For convenience, it will output a transposed (`column x selected_row`) matrix."
    )]
    Rows(TakeRowsArgs),

    #[command(
        about = "List column names",
        long_about = "List all column names in the backend.\n\
		      Useful for inspecting available features."
    )]
    ColumnNames(TakeColumnNamesArgs),

    #[command(
        about = "List row names",
        long_about = "List all row names in the backend.\n\
		      Useful for inspecting available samples or observations."
    )]
    RowNames(TakeRowNamesArgs),

    #[command(
        about = "Subset columns and create new backend",
        long_about = "Take columns from the sparse matrix and create a new sparse matrix backend.\n\
		      Allows for focused analysis on selected features."
    )]
    SubsetColumns(SubsetColumnsArgs),

    #[command(
        about = "Subset rows and create new backend",
        long_about = "Take rows from the sparse matrix and create a new sparse matrix backend.\n\
		      Allows for focused analysis on selected samples/observations."
    )]
    SubsetRows(SubsetRowsArgs),

    #[command(
        about = "Align data backends",
        long_about = "To ensure that column names are aligned for multimodal analysis.\n\
		      We will only keep columns and rows matched across files.\n\
		      1st row: `D(1,1)-D(1,2)`, 2nd row: `D(2,1)-D(2,2)`, etc.",
        visible_alias = "align"
    )]
    AlignData(AlignDataArgs),

    #[command(
        about = "Merge multiple `.mtx` files",
        long_about = "Merge multiple 10x `.mtx` files into one fileset.\n\
		      Useful for combining datasets from different sources."
    )]
    MergeMtx(MergeMtxArgs),

    #[command(
        about = "Merge multiple backend files",
        long_about = "Merge multiple backend file(sets) into one.\n\
		      Supports various formats and options for merging.",
        visible_alias = "merge"
    )]
    MergeBackend(MergeBackendArgs),

    #[command(
        about = "Squeeze out sparse rows/columns",
        long_about = "Squeeze out rows and columns with too few non-zeros.\n\
		      It will overwrite the original (be careful) and save the indices kept."
    )]
    Squeeze(RunSqueezeArgs),

    #[command(
        about = "Show basic matrix info",
        long_about = "Show basic information of a sparse matrix.\n\
		      If output header is provided, row and column names will be saved."
    )]
    Info(InfoArgs),

    #[command(
        about = "Take matrix statistics",
        long_about = "Take basic statistics from a sparse matrix.\n\
		      The output file will contain columns of \n\
		      (1) `nnz` - number of non-zero elements, \n\
		      (2) `tot` - total sum, \n\
		      (3) `mu` - average `μ`, \n\
		      (4) `sig` - standard deviation `σ`.",
        visible_alias = "stat"
    )]
    Statistics(RunStatArgs),

    #[command(
        about = "Simulate matrix with Gamma topic",
        long_about = "`Y(i,j) ~ δ(i,B(j)) Σ β(i,k) θ(j,k)` with β,θ ~ Gamma topic;\n\
		      B(j)`=batch; `ln δ`~N(0,1)"
    )]
    Simulate(RunSimulateArgs),

    #[command(about = "Simulate convoluted data matrix (experimental)")]
    SimulateConv(SimConvArgs),

    #[command(
        about = "Simulate multimodal count data with shared base + delta dictionaries",
        long_about = "Generate M count matrices from shared latent topics with modality-specific\n\
                      dictionaries: reference = softmax(W_base), others = softmax(W_base + W_delta_m).\n\
                      Delta is sparse (spike-and-slab): n_delta_features genes per topic are perturbed."
    )]
    SimulateMultimodal(RunSimulateMultimodalArgs),
}
