use crate::embed_common::*;
use crate::senna_input::*;

#[derive(Args, Debug)]
pub struct DeconvRegArgs {
    /// gene dictionary matrix file (generated by `topic`)
    /// (By default we assume it's logit-scaled).
    #[arg(short = 'g', long, required = true)]
    dict_file: Box<str>,

    /// bulk data files (`.parquet`, `.tsv.gz`, or `.csv.gz`)
    /// where the first column corresponds to gene names
    #[arg(short = 'x', long, required = true, value_delimiter = ',')]
    bulk_data_files: Vec<Box<str>>,

    /// single-cell data (`.zarr` or `.h5`)
    #[arg(short = 's', long, value_delimiter = ',')]
    sc_data_files: Option<Vec<Box<str>>>,

    /// batch membership files (comma-separated names). Each bach file
    /// should correspond to each data file.
    #[arg(long, short, value_delimiter(','))]
    batch_files: Option<Vec<Box<str>>>,

    /// preload all the single-cell columns data
    #[arg(long, default_value_t = false)]
    preload_data: bool,

    /// output header
    #[arg(long, short, required = true)]
    out: Box<str>,
}

pub fn fit_deconv_reg(args: &DeconvRegArgs) -> anyhow::Result<()> {
    let MatWithNames {
        rows: sc_genes,
        cols: _samples,
        mat: dict_dk,
    } = read_mat(&args.dict_file)?;

    info!("Read dictionary {} x {}", dict_dk.nrows(), dict_dk.ncols());

    let BulkDataOut {
        genes: _genes,
        samples: bulk_samples,
        data: bulk_dm,
    } = read_bulk_data_aligned(&args.bulk_data_files, &sc_genes)?;

    info!("Read bulk {} data file[s]", args.bulk_data_files.len());

    let bulk_cor_km = bulk_dm.correlate(&dict_dk)?;

    if let Some(sc_data_files) = args.sc_data_files.as_ref() {
        let SparseDataWithBatch {
            data: sc_data,
            batch: _batch,
            nbatch: _nbatch,
        } = read_data_on_shared_rows(ReadSharedRowsArgs {
            data_files: sc_data_files.clone(),
            batch_files: args.batch_files.clone(),
            preload: args.preload_data,
        })?;

        info!("Read single-cell data files");

        let sc_cor_kn = sc_data.correlate(&dict_dk)?;
        sc_cor_kn.transpose().to_parquet_with_names(
            &(args.out.to_string() + ".deconv.sc.parquet"),
            (Some(sc_data.column_names()?.as_ref()), None),
            None,
        )?;
    }

    bulk_cor_km.transpose().to_parquet_with_names(
        &(args.out.to_string() + ".deconv.parquet"),
        (Some(&bulk_samples), None),
        None,
    )?;

    Ok(())
}

trait CorrelateWithDictionary {
    /// `Σ_g ln(β[g,k]) * y[g,j] / Σ_g y[g,j]`
    fn correlate(&self, logits_dict_dk: &Mat) -> anyhow::Result<Mat>;
}

impl CorrelateWithDictionary for Mat {
    fn correlate(&self, logits_dict_dk: &Mat) -> anyhow::Result<Mat> {
        let denom_1n = self.row_sum().map(|x| x.clamp(1.0, f32::INFINITY));

        let mut ret = logits_dict_dk.transpose() * self.map(|x| x.clamp(0.0, f32::INFINITY));

        ret.row_iter_mut().for_each(|mut x| {
            x.component_div_assign(&denom_1n);
        });
        Ok(ret)
    }
}

impl CorrelateWithDictionary for SparseIoVec {
    fn correlate(&self, dict_dk: &Mat) -> anyhow::Result<Mat> {
        let mut cor_kn = Mat::zeros(dict_dk.ncols(), self.num_columns());
        self.visit_columns_by_block(&cor_with_dict, dict_dk, &mut cor_kn, None)?;
        Ok(cor_kn)
    }
}

fn cor_with_dict(
    (lb, ub): (usize, usize),
    data: &SparseIoVec,
    logits_dict_dk: &Mat,
    arc_num_kn: Arc<Mutex<&mut Mat>>,
) -> anyhow::Result<()> {
    let x_dn = data.read_columns_csc(lb..ub)?;
    let mut ret = (x_dn.transpose() * logits_dict_dk)
        .transpose()
        .map(|x| x.clamp(0.0, f32::INFINITY));
    let denom_1n =
        &x_dn * Mat::from_element(x_dn.ncols(), 1, 1.0).map(|x| x.clamp(1.0, f32::INFINITY));
    ret.row_iter_mut().for_each(|mut x| {
        x.component_div_assign(&denom_1n);
    });
    let mut cor_kn = arc_num_kn.lock().expect("lock");
    cor_kn.columns_range_mut(lb..ub).copy_from(&ret);
    Ok(())
}
