[package]
name = "chickpea"
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
bed-reader = { version = "1.0.6", default-features = false }
