[package]
name = "chickpea"
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
version = "0.4.0"

[lib]
name = "chickpea"
path = "src/lib.rs"

[[bin]]
name = "chickpea"
path = "src/main.rs"

[features]
default = []
cuda = [
    "legume-numeric/cuda",
    "data-beans/cuda",
    "graph-embedding-util/cuda",
]
metal = [
    "legume-numeric/metal",
    "data-beans/metal",
    "graph-embedding-util/metal",
]
hdf5 = ["data-beans/hdf5"]

[dependencies]
data-beans = { workspace = true, features = ["aux", "alg"] }
legume-numeric = { workspace = true, features = ["matrix", "param", "candle", "mcmc"] }
genomic-data = { workspace = true }
graph-embedding-util = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true }
flate2 = { workspace = true }
num_cpus = { workspace = true }
rayon = { workspace = true }
tempfile = { workspace = true }
rand = { workspace = true }
ndarray = { workspace = true }
ndarray-rand = { workspace = true }
rand_distr = { workspace = true }
nalgebra = { workspace = true }
nalgebra-sparse = { workspace = true }
approx = { workspace = true }

ctrlc = { workspace = true }
colored = { workspace = true }
special = { workspace = true }
indicatif = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
dashmap = { workspace = true }
rustc-hash = { workspace = true }

